### GET request to example server
GET https://examples.http-client.intellij.net/get
    ?generated-in=IntelliJ IDEA

###

### post insert user
POST http://localhost:8080/users
Content-Type: application/json

{
  "email": "test@agentflow.com",
  "password": "password123",
  "name": "AgentFlow"
}

### post login test
POST http://localhost:8080/auth/login
Content-Type: application/json

### ok
#{
#  "userId": 1,
#  "email": "bcrypt@agentflow.com",
#  "name": "BCrypt Test"
#}
### fail
#{
#  "email": "bcrypt@agentflow.com",
#  "password": "wrongPassword"
#}